### ISSUE TITLE
Any plans to switch to libsoup3?

### ISSUE THREAD

**Issue by MechDR** [louis77/tuner#103]
I'm trying to make a package of this app for Void Linux and the maintainers of Void are asking if there are any plans to switch to libsoup3 instead of libsoup2. I'm guessing because support for libsoup2 might be dropped in the foreseeable future (I think they switched from one package containing libsoup2 to another... my guess is exactly this).

**Comment by louis77** [comment]
Switching to libsoup2 wouldn't be too hard, but currently Tuner relies on geocode-lib to resolve the users position to a country code, which uses libsoup2. I have planned to remove these dependencies since I don't like the idea of using the Gnome Location Services just to get the users country. I'd rather have Tuner to ask the users for their country, since it is purely optional anyway.

I'll keep this open as a reminder and create a separate issue to remove the dependencies first.

**Comment by technosf** [comment]
1.5.2 Running on libsoup3

**Comment by th0razin3** [comment]
@technosf I added some more info regarding `libsoup3` for you to look at on codeberg.

**Comment by technosf** [comment]
@th0razin3 
Can you open a new issue ticket here with the error messages you are seeing. It builds and runs fine for me on Mint, but I do see plenty of warnings from _libsoup_, which I'll start looking into.

**Comment by th0razin3** [comment]
@technosf OK, will do.
