### ISSUE TITLE
After installation the new Flatpak of tuner 1.5.4; it do not start

### ISSUE THREAD

**Issue by Prust57** [louis77/tuner#142]
If I start tuner from terminal I get the following error

Failed to load module "xapp-gtk3-module"

** (com.github.louis77.tuner:2): CRITICAL **: 17:13:53.619: Settings.vala:87: Verbindung ist gescheitert: No such file or directory

my system
Linux Mint 22 Kernel 6.8.0-47

Regards

**Comment by technosf** [comment]
@Prust57 Would you be willing and able to run Tuner in a debug environment and step through it to get more info?

**Comment by Prust57** [comment]
Yes, I would do that. But you have to know that I am not an IT-Specialist.
Anyway tell me what I have to do and how I have to start the debug mode.
regards

**Comment by technosf** [comment]
I believe this is an issue with GLib.Settings in Window or Application: It should be getting built (See [Valadoc](https://valadoc.org/gio-2.0/GLib.Settings.html), but either isn't or wasn't included. Why the app is working for others if this is the case, TBD.

**Comment by technosf** [comment]
@Prust57 @ebpaul75 @jowuerg

Please take a look at [the Development doc ](https://github.com/louis77/tuner/blob/main/DEVELOP.md)

I would like to pin down in which release the issue was introduced. If you could set up a development environment:
```
git clone https://github.com/louis77/tuner.git
cd tuner
```
and then check out and run from the command line, in turn, tags _v1.5.4_, _v1.5.3_ and _1.5.2_: 
```
git checkout v1.5.4
meson setup --buildtype=debug builddir
ninja -C builddir
./builddir/com.github.louis77.tuner
```
See if you have the issue, and document messages on the command line.

Thank you for you help!

**Comment by technosf** [comment]
I have been looking at com.github.louis77.tuner.gschema.xml and wondering when it got compiled. Thanks @Prust57, I'll double down on that.

**Comment by nekrub2** [comment]
Had also a crash with this new version on LM22 cinnamon. The crash in systems says: 
The package providing /app/bin/com.github.louis77.tuner could not be found.
If you want to generate a stack trace for this crash report, please reinstall it.
Futhermore I found data in /tmp/mintreport/crash
[mintreport crash.zip](https://github.com/user-attachments/files/17443321/mintreport.crash.zip)

**Comment by Prust57** [comment]
Sorry I did not try with older versions because I'm a little bit busy at the moment. But in the annex you see my update list. It shows that my last version was 1.5.2 and it runs.

Then I tried the command from "angeld-jr2",  the result is that Tuner starts and run but I get the following messages:
Command:
flatpak --socket=system-bus run com.github.louis77.tuner

Gtk-Message: 08:49:33.164: Failed to load module "xapp-gtk3-module"
(com.github.louis77.tuner:2): Gtk-WARNING **: 08:49:33.674: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
** (com.github.louis77.tuner:2): WARNING **: 08:49:34.537: Window.vala:355: Auto-play enabled
** (com.github.louis77.tuner:2): WARNING **: 08:49:34.537: Window.vala:357: Last played station is: fccbd5cc-5583-4a25-9cad-f59e45156cf9
** (com.github.louis77.tuner:2): WARNING **: 08:49:34.633: Window.vala:439: storing last played station: fccbd5cc-5583-4a25-9cad-f59e45156cf9

![Tuner_02](https://github.com/user-attachments/assets/770a0cb6-c4d0-4912-a631-1cf523ed7fa6)

**Comment by Prust57** [comment]
Hi
So now I found a little bit time to build tuner like tags v1.5.4, v1.5.3 and 1.5.2
The result files you will find in the annex. The problem was that on v1.5.2 I can't check out.
But in my view the bug on tuner was not in v1.5.2. Earliest in v1.5.3 but I don't know.
I hope you will find out what is going wrong.
Regards

[tuner-v152.txt](https://github.com/user-attachments/files/17449639/tuner-v152.txt)
[tuner-v153.txt](https://github.com/user-attachments/files/17449640/tuner-v153.txt)
[tuner-v154.txt](https://github.com/user-attachments/files/17449641/tuner-v154.txt)

**Comment by Prust57** [comment]
Hi
Sorry. for my mistake. In the annex the new result file concerning 1.5.2

[tuner-152.txt](https://github.com/user-attachments/files/17463864/tuner-152.txt)

But you will see the result is the same. Anyway it's for me difficult to help. But if you have a new version do not hesitate to send it for testing.
At the moment I can live with the temporary solution of "angeld-jr2"  -> flatpak --socket=system-bus run com.github.louis77.tuner

Regards

**Comment by x-dean** [comment]
Same in Fedora Linux 40 (Workstation Edition)

**Comment by technosf** [comment]
With a lot of poking around I've found a few thing I'll throw out here for future reference:

- I didn't find the Python install scrips getting run, and ideally getting rid off it and having meson do the gschema install would be ideal.
- I found that  _ninja -C builddir_ didn't compile the gschema
- I found that _meson install -C builddir_ did compile the schema
- Once the schema is installed _meson compile -C builddir_ works, and so does _ninja -C builddir_
- I found that installing the icons happened before installing the schema
- I found that installing the icons was erring out because of looking for a _theme index_.
- I added a switch to the icon install to ignore missing _theme index_ 
- Running in the sandbox, Tuner theme changes work. Outside of the sandbox, theme is stuck.

With that, I've updated the development branch and rolled a flatpak on my clean system, and tuner finds the schema and runs. If you could try building the flatpak from _development_ to confirm, I'd appreciate it:
```bash
apt-get install flatpak-builder
flatpak remote-add --user --if-not-exists elementary https://flatpak.elementary.io/repo.flatpakrepo
flatpak install elementary io.elementary.Sdk//8 io.elementary.Platform//8
git checkout development
flatpak-builder --force-clean --user --sandbox --install build-dir com.github.louis77.tuner.yml
flatpak --user run com.github.louis77.tuner
```

Regarding getting local builds to run, the process requires the schema to be installed (but try the flatpak build first please, so as not to have local gschema hiding issues) :
```bash
rm -R builddir
meson setup --buildtype=debug builddir
meson install -C builddir
./builddir/com.github.louis77.tuner
```

Please let me know what you find. Thanks!

**Comment by bztd** [comment]
@technosf If the solution is not quick, I suggest applying the patch to the flathub package repository to temporarily fix the problem. Another solution is to grant the permission mentioned above, but I don't think that will happen.

**Comment by technosf** [comment]
@bztd I think the changes I put in place should address the issue with gschema not being installed (the Settings issues), which I could replicate on a clean system, and get fixed in a local flatpak build off the new development update. I wanted some validation before rolling a new release.

I can't speak to the permissions stuff from @angeld-jr2 - I built and installed it in the sandbox because it was a dev build... Release builds are not going into the sandbox AFAIK.  

If theres more I should know, please if you could expound as I am coming to flatpaks without prior experience :)

**Comment by bztd** [comment]
In fact, I haven't reviewed the code enough to understand why the error occurred. I only identified the part of the code that was causing it (I thought it was due to an attempt to identify the theme through the system D-Bus, which it doesn't have access to).
For the Flathub repository, could you create a beta branch to test the fixes, or simply make them and not merge them into the main branch so we have a testing package?

**Comment by technosf** [comment]
I had opened #143 for theme issues etc. As I mentioned, on my fresh system, themes work when run in the sandbox. Themes don't work on my main system. Some testing to do... But themes aren't read by the app, only the _prefer dark_ preference is twiddled

This ticket I think the only issue is GIO Setting schema not getting compile - that was causing the crashes, and hopefully the fix is in the development branch now.

**Comment by bztd** [comment]
The problem does not occur in the compilation:

https://github.com/flathub/com.github.louis77.tuner/pull/14

**Comment by technosf** [comment]
@bztd that install gives me:
```
** (com.github.louis77.tuner:2): WARNING **: 13:52:07.558: Application.vala:81: Settings path: /com/github/louis77/tuner/
Gtk-Message: 13:52:07.565: Failed to load module "xapp-gtk3-module"

** (com.github.louis77.tuner:2): CRITICAL **: 13:52:07.684: Settings.vala:87: Could not connect: No such file or directory

** (com.github.louis77.tuner:2): CRITICAL **: 13:52:07.684: Settings.vala:107: Could not connect: No such file or directory
```

@Prust57 - same for you?
@bztd  - I'd like to set up a flathub beta repo - could you help? Hit me up on Discourse pls.

**Comment by bztd** [comment]
@technosf  Just create a branch in the repository with the name "beta"

**Comment by bztd** [comment]
The program runs normally. The output:

** (com.github.louis77.tuner:9): WARNING **: 18:19:29.243: Application.vala:81: Settings path: /com/github/louis77/tuner/
Gtk-Message: 18:19:29.246: Failed to load module "xapp-gtk3-module"

In my case I run:

flatpak run --branch=test com.github.louis77.tuner

I don't think I have residual configuration. I will do a clean installation to confirm.

**Comment by Prust57** [comment]
For me the same, see following (on both commands the same):
flatpak run com.github.louis77.tuner
flatpak run --branch=test com.github.louis77.tuner

** (com.github.louis77.tuner:2): WARNING **: 10:13:37.575: Application.vala:81: Settings path: /com/github/louis77/tuner/
Gtk-Message: 10:13:37.582: Failed to load module "xapp-gtk3-module"
** (com.github.louis77.tuner:2): CRITICAL **: 10:13:37.702: Settings.vala:87: Verbindung ist gescheitert: No such file or directory
** (com.github.louis77.tuner:2): CRITICAL **: 10:13:37.703: Settings.vala:107: Verbindung ist gescheitert: No such file or directory

Regards, Pius

**Comment by bztd** [comment]
On my PC it runs normally. It seems to be due to a residual configuration, it has happened to me before but this time I can't find the configuration that is being overwritten.

Could you try:

flatpak install --user https://dl.flathub.org/build-repo/140749/com.github.louis77.tuner.flatpakref

It should work. If so, I suggest you merge it to solve the problem.

**Comment by bztd** [comment]
@technosf Have you made a working local build for the org.freedesktop.Platform runtime, because I see that it is suggested to use the elementary SDK?

**Comment by technosf** [comment]
@bztd I have not made a working local build for the org.freedesktop.Platform runtime, I am using Elementary.
Talking of residual configurations - I have found that on the fresh Mint install I did. After trying various builds, a build that didn't work because of the missing _gschema_ started working, and on looking for _gchema.compiled_ file didn't find any, nor _com.github.louis77.tuner.gschema.xml_ files. I am going to flush that system again.

I pushed the flathub request #15 - I would like a better understanding of what the Windows patch does, in that I want to clarify if it's to facilitate how the build is done, or a code change that should be rolled into the Tuner repo and the patch removed from a future release?

**Comment by technosf** [comment]
@Prust57 - these are informational messages. They are coded as 'warnings' as 'debug' messages have to be enabled, and it's not clear how to have the app know that. Warnings work. Favicon messages - they are more varied due to station favicons urls producing all kinds of files, the invalid ones being ignored but logged.
```
** (com.github.louis77.tuner:2): WARNING **: 07:40:11.309: Window.vala:353: Auto-play enabled
** (com.github.louis77.tuner:2): WARNING **: 07:40:11.309: Window.vala:355: Last played station is: fccbd5cc-5583-4a25-9cad-f59e45156cf9
** (com.github.louis77.tuner:2): WARNING **: 07:40:11.647: Window.vala:437: storing last played station: fccbd5cc-5583-4a25-9cad-f59e45156cf9
** (com.github.louis77.tuner:2): WARNING **: 07:40:12.437: Favicon.vala:66: Failed to process favicon https://ibb.co/jZsV775: Format der Bilddatei unbekannt
```

**Comment by technosf** [comment]
@bztd Committed the flathub build, scrubbed my test system, and installed the build (now the stable build). The gschema did get installed and Tuner works.

@Prust57 - can you purge, reload Tuner from the main repo and give it a try? To check if the gschema got installed:
`
updatedb
locate louis77|grep gschema
`

**Comment by Prust57** [comment]
Hi technosf,

Concerning your last post I did the following steps:
- Install in my Virtualbox a new Linux Mint 22 machine
- Install tuner flatpak  (v1.5.4) from Linux Mint repository 
- Start tuner
I was very astonished to see that tuner started. Therefore I'm a little bit confusing. All this steps I did in the last weeks often and always tuner didn't start.

Also I did start
updatedb
locate louis77 | grep gschema
Result:
pius@pius-VirtualBox:~$ sudo updatedb
pius@pius-VirtualBox:~$ locate louis77 | grep gschema
/var/lib/flatpak/app/com.github.louis77.tuner/x86_64/stable/df7043b5b39e45a03f6f65b9171236ae77f7e4895776ef8b20e317fe619f26b2/files/share/glib-2.0/schemas/com.github.louis77.tuner.gschema.xml
/var/lib/flatpak/app/com.github.louis77.tuner/x86_64/stable/df7043b5b39e45a03f6f65b9171236ae77f7e4895776ef8b20e317fe619f26b2/files/share/glib-2.0/schemas/gschemas.compiled

Therefore I hat a look at my notebook to test the same. Then in past I had with tuner the same problem like desktop computer.
- Uninstall and purge the current tuner.
- Install tuner flatpak (v1.5.4) from Linux Mint repository
- Start tuner

The same behavior like desktop computer
sudo updatedb
pius@900X3C:~$ locate louis77 | grep gschema
/var/lib/flatpak/app/com.github.louis77.tuner/x86_64/stable/df7043b5b39e45a03f6f65b9171236ae77f7e4895776ef8b20e317fe619f26b2/files/share/glib-2.0/schemas/com.github.louis77.tuner.gschema.xml
/var/lib/flatpak/app/com.github.louis77.tuner/x86_64/stable/df7043b5b39e45a03f6f65b9171236ae77f7e4895776ef8b20e317fe619f26b2/files/share/glib-2.0/schemas/gschemas.compiled

I don't know why tuner didn't run in the last weeks? Maybe it's about kernel? I did an update to Kernel 6.8.0-48?

Regards

**Comment by technosf** [comment]
@Prust57 - Search is dodgy on 1.5.4 because it has to run that on radio-browser. 1.5.5 will address it.
The gschema stuff - I can't tell you why the issues happened conclusively, but I think the install got hung in certain situations and the gschema located successfully.

  I am going to close this and move on to 1.5.5 - if this issue reoccurs we'll open a new ticket.

Thanks everyone for your help!
