### ISSUE TITLE
Play in background

### ISSUE THREAD

**Issue by dcowan-london** [louis77/tuner#67]
Hi,
Until eOS6, I used Melody (https://github.com/artemanufrij/playmymusic) for playing streams. Melody has not been updated for the new AppCenter packaging, so I went looking for an alternative - and found Tuner.

First of all, thank you! Tuner looks and works great.

I have a few requests/suggestions:

* An option to display stations as a one list, instead of two parallel lists
* An option to choose a pane to open on. I'd usually want to go directly to Starred by You when opening Tuner.
* Not sure if this is possible, but showing the currently playing song (with station - so eg "Song - Station") in the Music Wingpanel 
plugin.
* And really the biggest one for me - background play. Melody allowed me to close the app, and it would continue playing.

Thank you again!

**Comment by louis77** [comment]
Hi @dcowan-london

Thank you so much for your valuable feedback. All your points/feature requests make total sense and I'll put them into the readmap for the next release. I keep you posted here.

**Comment by adql** [comment]
A minor thing with background playback not worth its own issue: when reopening the player it is not focused as intuitively expected (by many I suppose). On a tiling WM this can be pretty confusing when the windows are tabbed.

Also, consider making background playback optional, since it has added additional mouse interaction when just wanting to stop the radio and close the player (again, mostly for tiling WM users, but also for ctrl-f4 fans).

Really thanks for the great work! I like its lightweight spirit.

**Comment by technosf** [comment]
Need preferences to better manage features. 
Work those off [#77 ](https://github.com/louis77/tuner/issues/77)
